### PR TITLE
Add simple code minifications

### PR DESCRIPTION
**Pull request by NeeEoo**
Removes `><`, `<>`, `+-` and `-+` from the compiled code.

### CODE REVIEW

**Comment by NeeEoo** [comment]
The minification could maybe be enabled by a command argument flag.

**Comment by elikaski** [comment]
Great feature, thanks!
I reviewed your code and it looks good

> The minification could maybe be enabled by a command argument flag.

I agree
Would you like to add it or should I just merge?

**Comment by NeeEoo** [comment]
Any idea what letter the command argument should be. `-O` for optimize, `-p` for production, `-m` for minify, or something else.

**Comment by elikaski** [comment]
I think `-m` is best

**Comment by NeeEoo** [comment]
Uses -m and --minify to enable minification.

**Pull request merged**
