### PR TITLE
Nee eoo switch case

### PR DESCRIPTION
**Pull request by elikaski**

### CODE REVIEW

**Comment by NeeEoo** [comment]
You will have to revert the revert i think

**Comment by NeeEoo** [comment]
Wait ill try to reopen a fresh one

**Comment by elikaski** [comment]
I can force push master to before the merge. Like going back in time ;)

**Comment by NeeEoo** [comment]
You would still have to revert the revert. I think. I can open a new pull request with all of the changes instead

**Comment by elikaski** [comment]
I think it worked now :)

**Comment by NeeEoo** [comment]
Yep i think it did

**Comment by NeeEoo** [comment]
Even got the revert commits removed

**Comment by elikaski** [comment]
Thanks for all your help with implementing this :)

**Comment by NeeEoo** [comment]
I think the next pull request should be the for loop scope as that fixes my tetris game

**Pull request merged**
